### ISSUE TITLE
Exception on non-ascii filenames

### ISSUE THREAD

**Issue by paour** [letorbi/inotifyrecursive#6]
I've noticed that the script was sometimes stopping, so I ran it with a trace, and here's where it happened:

```
Event(wd=21322, mask=256, cookie=0, name='.1-03 Strasbourg\xef\xbc\x8fst. Denis.m4a.9EVdx4')
2019-12-04 07:37:16,843 ERROR An uncaught exception occurred
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/synoindexwatcher/__main__.py", line 121, in <module>
    start()
  File "/usr/lib/python2.7/site-packages/synoindexwatcher/__main__.py", line 101, in start
    path = os.path.join(inotify.get_path(event.wd), str.encode(event.name))
UnicodeDecodeError: 'ascii' codec can't decode byte 0xef in position 16: ordinal not in range(128)
```

The name of the affected file is `1-03 Strasbourg／st. Denis.m4a`, with the slash being a Unicode character.

I know Python is pretty annoying when it comes to unicode, but here would it not just be a matter of replacing `str.encode` with `unicode.encode`?

**Comment by letorbi** [comment]
Thanks for reporting this problem. I've re-investiged the string-encoding and in the end it turned out that we don't need to do any explicit en/decoding at all :smile: 

The problem should be fixed with 2e3846c7dda6e277216c4cc3832d1dc502e83eab. I've also removed any explicit string-encoding from Synoindex Watcher ([149c07f](https://github.com/letorbi/synoindexwatcher/commit/149c07f5e931ab2900609af3062e9fd50e20fa92)) and updated the inotify-recursive dependency ([5137cea](https://github.com/letorbi/synoindexwatcher/commit/5137ceaa4427066356b54b0b9101c4ede12df5de)).

Just update with `sudo python -m pip install --upgrade https://github.com/letorbi/synoindexwatcher/archive/master.zip` and you should be fine.
