### ISSUE TITLE
0.8.1 still fails on Unicode filenames

### ISSUE THREAD

**Issue by paour** [letorbi/inotifyrecursive#7]
The attempt to fix the [previously reported exception](https://github.com/letorbi/inotifyrecursive/issues/6) was not entirely successful, but I don't think I can reopen an issue so here's a new one…

After using pip to upgrade this package (resulting in `Successfully installed inotifyrecursive-0.2.3 synoindexwatcher-0.8.1` – just making sure the version numbers are as expected), I get a slightly different exception:

```
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/synoindexwatcher/__main__.py", line 203, in <module>
    start()
  File "/usr/lib/python2.7/site-packages/synoindexwatcher/__main__.py", line 185, in start
    fullpath = os.path.join(inotify.get_path(event.wd), event.name)
  File "/usr/lib/python2.7/posixpath.py", line 73, in join
    path += '/' + b
UnicodeDecodeError: 'ascii' codec can't decode byte 0xef in position 16: ordinal not in range(128)
```

Obviously, though it doesn't seem to be documented in the Python man pages, `os.path.join` does expect a decoded path.

**Comment by letorbi** [comment]
Ok great :D I'm closing this issue then. Thanks for reporting.

I've also updated the dependencies of Synoindex Watcher to ensure that everyone gets the fixed *inotifyrecusive* packages after upgrading with `python -m pip install --upgrade https://github.com/letorbi/synoindexwatcher/archive/master.zip`.

BTW: I've moved the issue to the *inotifyrecusive* repo, since the problem was there again.
