### ISSUE TITLE
Changes in inotify_simple broke things

### ISSUE THREAD

**Issue by chrisjbillington** [letorbi/inotifyrecursive#8]
Hi! I'm the developer of inotify_simple. I noticed that some changes in inotify_simple 1.3 (just released), though they were intended to be backward compatible, have broken your project somewhat.

Firstly you  are using `inotify_simple._fsencode(path)`. That's been removed from inotify_simple (there was an underscore in front of it so it wasn't a guarantee anyway :p ). You could still use it if you wanted (it no longer has the prefixed underscore), but actually I think there's an issue with that line being in your code.

On Python 3, inotify_simple will already fsencode the paths being passed to it, and will fsdecode them when it returns them in Event objects. So if you want these paths to pass equality checks with each other, such as looking them up in dictionaries (which I see you're doing), this will not work on Python 3 - the byestrings resulting from fsencoding yourself will not be equal to the unicode strings returned in Event objects.

This looks like an actual problem: your 'info' nested dictionary has byestrings as keys for filepaths (as set in __add_info and __set_info), but later the lookup based on the name in the Event objects (in read()) are unicode strings. This is the case in Python 3 anyway, on Py2 unicode and bytestrings pass equality checks.

I would recommend only fsencoding if the code is running on Python 2 (in which case the names returned in Event objects are bytestrings too so it's all good). If you're on Python 3, just keep everything unicode - in fact if the user passes you a byestring, you should fsdecode it and keep the unicode string in your data structures.

(or just drop Python 2 support and don't deal with fsdecode at all)

The other issue is that you did an `import *` of `inotify_simple`, and then used `inotify_simple` as a name. I never intended the inotify_simple submodule itself to be in an `import *`, and it's not anymore.

Looks like you could either drop all the `inotify_simple` prefixes from references to the module's attributes, or just do `import inotify_simple` instead.

**Comment by letorbi** [comment]
Hej Chris,

thank you for telling me about the upstream changes and the suggestions on how to improve the handling of strings. I actually wanted to ask you about your opinion on *inotifyrecursive* some time ago - but then life kicked-in ;)

Since I don't have much time at the moment, I've just locked the *inotify_simple* dependency on version 1.2.1. This should prevent problems due to API changes.

Luckily the string-conversion problems are not that critical, since *synoindexwatcher*, the only project that depends on *inotifyrecursive* right now, is meant to be used on Synology DiskStations with Python 2.

However, I'm going to fix all issues you've mentioned ASAP - I just don't know when this will be ;) Feel free to post more improvement suggestions, if you have.

Regards,
Torben

**Comment by letorbi** [comment]
The problems should be fixed with 4dcf54a4e8c9191ecbf7f1698c52ed638209ba99 and c7fe98d435989365a3e363f7657fb4fc7cb57c20. Please reopen the issue, if you still see or experience problems.

**Comment by chrisjbillington** [comment]
Those fixes look good to me! I think that is the correct behaviour for both Python 2 and Python 3.
